import React, {Suspense} from "react";
import Head from 'next/head';
import {Canvas} from "@react-three/fiber";

import DirectionalLight from "@/features/core/components/DirectionalLight";
import AmbientLight from "@/features/core/components/AmbientLight";
import OrbitControls from "@/features/core/components/OrbitControls";
import Draggable from "@/features/core/components/Draggable";
import {generateBoxCoordinates} from "@/features/core//utils/utils";

import SceneBackground from "@/features/playground/components/SceneBackground";
import Plane from "@/features/playground/components/Plane";
import Box from "@/features/playground/components/Box";
import RocketModel from "@/features/playground/components/RocketModel";
import AdventureCoreModel from "@/features/playground/components/AdventureCoreModel";
import ZombieModel from "@/features/playground/components/ZombieModel";
import ParticleSystem from "@/features/core/components/ParticleSystem";
import {Stats} from "@react-three/drei";
import {Vector3} from "three";
import {RectAreaLightUniformsLib} from "three/examples/jsm/lights/RectAreaLightUniformsLib";


export default function Home() {
    const boxCoords = generateBoxCoordinates();
    // RectAreaLightUniformsLib.init();

    return (
        <>
        <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>
        <main className="w-11/12 h-screen"> {/* change to w-screen */}
            <Canvas
                shadows={true}
                camera={{
                    fov: 60,
                    aspect: 1920/1080,
                    near: 1.0,
                    far: 1000.0,
                    position: [75, 20, 0]
                }}>

                {/* Just adds additional Light to the scene */}
                <AmbientLight/>

                {/* Different Colors for Top and Bottom */}
                {/*<hemisphereLight color="#FFFF80" groundColor="#4040FF" intensity={1.0}/>*/}

                {/* For Portals, Wall light? */}
                {/*<rectAreaLight color="#FFFFFF" intensity={1.0}*/}
                {/*               width={20.0} height={20.0}*/}
                {/*               position={[0, 10, 0]}/>*/}

                {/* Main source of Light(Sun)... */}
                <DirectionalLight/>

                {/*<mesh position={[0, 40, 0]} scale={[2, 2, 2]}>*/}
                {/*    <Box />*/}
                {/*     For lamps, explosions, ... . Dont have a specific direction */}
                {/*    <pointLight color="#FFFFFF" intensity={1.0} distance={100} position={[0, -2, 0]}/>*/}
                {/*</mesh>*/}

                {/* Have specific pos and direction (like a flashlight) */}
                {/*<spotLight color="#FFFFFF" intensity={1.0}*/}
                {/*           distance={2000.0} angle={Math.PI / 2.0}*/}
                {/*           penumbra={0.5} decay={0.3}*/}
                {/*           position={[5, 12, 0]} target-position={[-1, 0, 0]} />*/}


                <OrbitControls/>
                <SceneBackground/>
                <Plane/>

                {boxCoords.map((pos, ind) =>
                    <Box key={ind} position={pos}/>
                )}
                <Suspense fallback={null}>
                    <RocketModel scale={[2, 2, 2]} position={[400, 140, 0]}/>
                    <ZombieModel/>
                    {/*<AdventureCoreModel scale={[0.01, 0.01, 0.01]} />*/}
                </Suspense>
                <Box position={[20, 10, 0]} scale={[2, 2, 2]}/>

                {/*<Draggable>*/}
                {/*    <Suspense fallback={null}>*/}
                {/*        <Box rotateX={3} rotateY={0.2}/>*/}
                {/*    </Suspense>*/}
                {/*</Draggable>*/}

                <Stats />
            </Canvas>
        </main>
        </>
    )
}
