import React from "react";
import Head from 'next/head';
import {Canvas} from "@react-three/fiber";

import DirectionalLight from "@/components/DirectionalLight";
import AmbientLight from "@/components/AmbientLight";
import OrbitControls from "@/components/OrbitControls";
import SceneBackground from "@/components/SceneBackground";
import Plane from "@/components/Plane";
import Box from "@/components/Box";
import {cookies} from "next/headers";
// import Draggable from "@/components/Draggable";


export default function Home() {
    function generateBoxCoordinates(){
        const coords: [x:number, y:number, z:number][] = [];
        for (let x = -8; x < 8; x++) {
            for (let y = -8; y < 8; y++) {
                coords.push([Math.random() + x * 5, Math.random() * 4.0 + 2.0, Math.random() + y * 5]);
            }
        }
        return coords;
    }
    const boxCoords = generateBoxCoordinates();

    return (
        <>
        <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>
        <main className="w-11/12 h-screen"> {/* change to w-screen */}
            <Canvas
                shadows={true}
                camera={{
                    fov: 60,
                    aspect: 1920/1080,
                    near: 1.0,
                    far: 1000.0,
                    position: [75, 20, 0]
                }}>
                <DirectionalLight/>
                <AmbientLight/>
                <OrbitControls/>
                <SceneBackground/>
                <Plane/>

                {boxCoords.map((pos, ind) =>
                    <Box key={ind} position={pos}/>
                )}

                {/*<Draggable>*/}
                {/*    <Suspense fallback={null}>*/}
                {/*        <Box rotateX={3} rotateY={0.2}/>*/}
                {/*    </Suspense>*/}
                {/*</Draggable>*/}
            </Canvas>
        </main>
        </>
    )
}
