import React, {Suspense} from "react";
import Head from 'next/head';
import {Canvas} from "@react-three/fiber";

import DirectionalLight from "@/features/core/components/DirectionalLight";
import AmbientLight from "@/features/core/components/AmbientLight";
import OrbitControls from "@/features/core/components/OrbitControls";
import Draggable from "@/features/core/components/Draggable";
import {generateBoxCoordinates} from "@/features/core/utils";

import SceneBackground from "@/features/playground/components/SceneBackground";
import Plane from "@/features/playground/components/Plane";
import Box from "@/features/playground/components/Box";
import RocketModel from "@/features/playground/components/RocketModel";
import AdventureCoreModel from "@/features/playground/components/AdventureCoreModel";
import ZombieModel from "@/features/playground/components/ZombieModel";


export default function Home() {
    // const boxCoords = generateBoxCoordinates();

    return (
        <>
        <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>
        <main className="w-11/12 h-screen"> {/* change to w-screen */}
            <Canvas
                shadows={true}
                camera={{
                    fov: 60,
                    aspect: 1920/1080,
                    near: 1.0,
                    far: 1000.0,
                    position: [75, 20, 0]
                }}>
                <DirectionalLight/>
                <AmbientLight/>
                <OrbitControls/>
                <SceneBackground/>
                <Plane/>

                {/*{boxCoords.map((pos, ind) =>*/}
                {/*    <Box key={ind} position={pos}/>*/}
                {/*)}*/}
                <Suspense fallback={null}>
                    <RocketModel scale={[2, 2, 2]}/>
                    {/*<AdventureCoreModel scale={[0.01, 0.01, 0.01]} />*/}
                    {/*<ZombieModel/>*/}
                </Suspense>
                {/*<BaseGLTFModel path="models/adventure_core/scene.gltf"/>*/}

                {/*<BaseGLTFModel path="models/rocket_model/Rocket_Ship_01.gltf"/>*/}
                {/*<BaseGLTFModel path="models/portal_gun/scene.gltf"/>*/}

                {/*<Draggable>*/}
                {/*    <Suspense fallback={null}>*/}
                {/*        <Box rotateX={3} rotateY={0.2}/>*/}
                {/*    </Suspense>*/}
                {/*</Draggable>*/}
            </Canvas>
        </main>
        </>
    )
}
