import React, {Suspense, useRef} from "react";

import {useLoader} from "@react-three/fiber";
import { useGLTF } from '@react-three/drei';
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader";


const PATH = 'models/rocket_model/Rocket_Ship_01.gltf';


const RocketModel = (props: any) => {
    const gltf = useLoader(GLTFLoader, PATH);
    return (
        <Suspense fallback={null}>
            <primitive {...props} object={gltf.scene}/>
        </Suspense>
    );
};



// Auto-generated by: https://github.com/pmndrs/gltfjsx
// const RocketModel = (props: any) => {
//   const group = useRef();
//   const { nodes, materials } = useGLTF(PATH);
//
//     return (
//     <group ref={group} {...props} dispose={null}>
//       <mesh
//         castShadow={true}
//         receiveShadow={true}
//         geometry={nodes['buffer-0-mesh-0'].geometry}
//         material={materials.F44336}
//       />
//       <mesh
//         castShadow={true}
//         receiveShadow={true}
//         geometry={nodes['buffer-0-mesh-0_1'].geometry}
//         material={materials.FFFFFF}
//       />
//       <mesh
//         castShadow={true}
//         receiveShadow={true}
//         geometry={nodes['buffer-0-mesh-0_2'].geometry}
//         material={materials['455A64']}
//       />
//       <mesh
//         castShadow={true}
//         receiveShadow={true}
//         geometry={nodes['buffer-0-mesh-0_3'].geometry}
//         material={materials['78909C']}
//       />
//       <mesh
//         castShadow={true}
//         receiveShadow={true}
//         geometry={nodes['buffer-0-mesh-0_4'].geometry}
//         material={materials['80DEEA']}
//       />
//     </group>
//   );
// };
// useGLTF.preload(PATH);


export default RocketModel;
